# Generated by Django 4.1.7 on 2023-10-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='views',
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
