# Generated by Django 4.2.4 on 2023-09-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('album_image', models.ImageField(default='ATL.jpeg', upload_to='')),
                ('is_uploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='add_my',
            field=models.ManyToManyField(blank=True, related_name='my_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Uploaded_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('song', models.FileField(upload_to='')),
                ('chosen', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to='music_player.album')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=255)),
                ('singer_image', models.ImageField(default='6120361940.jpg', upload_to='')),
                ('album', models.ManyToManyField(blank=True, related_name='singer', to='music_player.album')),
                ('songs', models.ManyToManyField(blank=True, related_name='singer', to='music_player.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_singer', to='music_player.singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_player.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_singer', to='music_player.singer'),
        ),
    ]
