# Generated by Django 4.1.7 on 2023-09-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to=''),
        ),
    ]
