# Generated by Django 4.2.4 on 2023-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_album_song_add_my_alter_song_song_uploaded_song_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=255)),
                ('songs', models.ManyToManyField(related_name='playlist', to='music_player.song')),
            ],
        ),
    ]
