# Generated by Django 4.2.4 on 2023-09-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_album_song_image_alter_song_song_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='album_image',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='image',
            new_name='song_image',
        ),
    ]
