# Generated by Django 4.2.4 on 2023-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_rename_image_album_album_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
