# Generated by Django 4.2.4 on 2023-10-02 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0004_playlist_user_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist_adding',
            field=models.ManyToManyField(blank=True, related_name='playlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
