# Generated by Django 4.2.4 on 2023-10-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0004_uploaded_song_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
