# Generated by Django 4.2.4 on 2023-10-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_album_review'),
        ('music_player', '0005_album_is_new_song_is_new'),
    ]

    operations = [
    ]
