# Generated by Django 4.2.4 on 2023-10-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0005_song_playlist_adding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist_adding',
        ),
    ]
