# Generated by Django 4.2.4 on 2023-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0006_alter_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
