# Generated by Django 4.2.4 on 2023-10-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0006_remove_song_playlist_adding'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_song',
            name='song_singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_song_singer', to='music_player.singer'),
        ),
    ]
