# Generated by Django 4.1.7 on 2023-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0007_remove_song_singer_album_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_new',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
