# Generated by Django 4.1.7 on 2023-09-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0008_song_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_new',
        ),
    ]
