# Generated by Django 4.1.7 on 2023-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0009_remove_song_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
