# Generated by Django 4.1.7 on 2023-10-09 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0009_song_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_views',
            field=models.ManyToManyField(related_name='singer_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
