# Generated by Django 4.1.7 on 2023-10-09 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0010_singer_singer_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='singer_views',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='songs',
        ),
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.ManyToManyField(related_name='album_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
