# Generated by Django 4.1.7 on 2023-09-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0010_album_is_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('song', models.FileField(upload_to='')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to='music_player.album')),
            ],
        ),
    ]
