# Generated by Django 4.1.7 on 2023-10-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0010_alter_song_dislikes_alter_song_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Хип-хоп', 'Хип-хоп'), ('Рок', 'Рок'), ('Поп', 'Поп'), ('Хард-рок', 'Хард-рок')], max_length=255)),
            ],
        ),
    ]
