# Generated by Django 4.2.4 on 2023-10-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0010_singer_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_album', models.ManyToManyField(blank=True, related_name='notify_album', to='music_player.album')),
                ('notify_song', models.ManyToManyField(blank=True, related_name='notify_song', to='music_player.song')),
                ('notify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
