# Generated by Django 4.2.4 on 2023-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0011_remove_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='ATL.jpeg', upload_to=''),
        ),
    ]
