# Generated by Django 4.1.7 on 2023-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0011_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Хип-хоп', 'Хип-хоп'), ('Рок', 'Рок'), ('Поп', 'Поп'), ('Хард-рок', 'Хард-рок')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
