# Generated by Django 4.1.7 on 2023-09-18 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0011_uploaded_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='add_my',
            field=models.ManyToManyField(related_name='my_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
