# Generated by Django 4.2.4 on 2023-10-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0012_notificaton_notify_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaton',
            name='notify_album',
        ),
        migrations.RemoveField(
            model_name='notificaton',
            name='notify_singer',
        ),
        migrations.RemoveField(
            model_name='notificaton',
            name='notify_song',
        ),
        migrations.CreateModel(
            name='Notification_objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notufy', to='music_player.notificaton')),
                ('notify_album', models.ManyToManyField(blank=True, related_name='notify_album', to='music_player.album')),
                ('notify_singer', models.ManyToManyField(blank=True, related_name='notify_singer', to='music_player.singer')),
                ('notify_song', models.ManyToManyField(blank=True, related_name='notify_song', to='music_player.song')),
            ],
        ),
    ]
