# Generated by Django 4.2.4 on 2023-09-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0012_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
    ]
