# Generated by Django 4.1.7 on 2023-10-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0012_remove_album_views_singer_album_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='album_quantity',
        ),
    ]
