# Generated by Django 4.1.7 on 2023-09-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0012_song_add_my'),
        ('music_player', '0013_remove_song_chosen_uploaded_song_chosen'),
    ]

    operations = [
    ]
