# Generated by Django 4.2.4 on 2023-10-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0013_remove_notificaton_notify_album_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification_objects',
            new_name='Notification_object',
        ),
    ]
