# Generated by Django 4.2.4 on 2023-09-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0014_song_add_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='singer',
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=255)),
                ('album', models.ManyToManyField(related_name='singer', to='music_player.album')),
                ('songs', models.ManyToManyField(related_name='singer', to='music_player.song')),
            ],
        ),
    ]
