# Generated by Django 4.2.4 on 2023-10-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0014_rename_notification_objects_notification_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_object',
            name='notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='music_player.notificaton'),
        ),
    ]
