# Generated by Django 4.2.4 on 2023-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0015_alter_notification_object_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_object',
            name='deleted_things',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
