# Generated by Django 4.2.4 on 2023-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0015_remove_album_singer_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='singer', to='music_player.album'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='singer', to='music_player.song'),
        ),
    ]
