# Generated by Django 4.2.4 on 2023-09-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0016_alter_singer_album_alter_singer_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_singer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album_singer', to='music_player.singer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_singer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='song_singer', to='music_player.singer'),
            preserve_default=False,
        ),
    ]
