# Generated by Django 4.2.4 on 2023-09-20 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0017_album_album_singer_song_song_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='add_my',
            field=models.ManyToManyField(blank=True, related_name='my_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
