# Generated by Django 4.2.4 on 2023-09-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0018_alter_song_add_my'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_image',
            field=models.ImageField(default='6120361940.jpg', upload_to=''),
        ),
    ]
